#!/usr/bin/env bash
source "$LIBRARIUM_ROOT/install/install.sh"

COMPILED_DIR="$HOME/.cache/librarium/compiled"
INSTALLED_PLUGINS_DIR="$PLUGIN_INSTALL_DIR"

log_info "Compiling plugins..."
mkdir -p "$COMPILED_DIR"

# Clear old compiled files
rm -f "$COMPILED_DIR"/*.fish

for plugin_path in "$INSTALLED_PLUGINS_DIR"/*; do
    if [ -d "$plugin_path" ]; then
        plugin_name=$(basename "$plugin_path")
        compiled_file="$COMPILED_DIR/$plugin_name.fish"
        
        log_info "-> Compiling $plugin_name..."
        
        # Add a header to the compiled file
        echo "# Compiled plugin pack for $plugin_name - auto-generated by Librarium" > "$compiled_file"
        
        # Find all .fish files and append them to the compiled pack
        find "$plugin_path" -name '*.fish' -print0 | xargs -0 cat >> "$compiled_file"
        
        log_info "  - Created pack at $compiled_file"
    fi
done

log_success "All plugins compiled successfully."
